apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
data:
  CLIENT_URLS: {{ .Values.config.clientUrls | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  MONGO_URI: "mongodb://{{ .Values.config.mongoUriHost }}/streamingapp"
